repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        exclude: ^experimental/
        entry: poetry run black
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        exclude: ^experimental/
        entry: poetry run pylint
        language: system
        types: [python]
    -   id: mypy
        name: mypy
        exclude: ^experimental/
        entry: poetry run mypy
        language: system
        types: [python]
